USE [master]
GO

/****** Object:  Database [PromoPilotDB]    Script Date: 07-11-2025 11:26:51 ******/
CREATE DATABASE [PromoPilotDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PromoPilotDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PromoPilotDB.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PromoPilotDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PromoPilotDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PromoPilotDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PromoPilotDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PromoPilotDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PromoPilotDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PromoPilotDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PromoPilotDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PromoPilotDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PromoPilotDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PromoPilotDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PromoPilotDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PromoPilotDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PromoPilotDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PromoPilotDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PromoPilotDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PromoPilotDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PromoPilotDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PromoPilotDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PromoPilotDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PromoPilotDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PromoPilotDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PromoPilotDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PromoPilotDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PromoPilotDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PromoPilotDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PromoPilotDB] SET  MULTI_USER 
GO

ALTER DATABASE [PromoPilotDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PromoPilotDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PromoPilotDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PromoPilotDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PromoPilotDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PromoPilotDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PromoPilotDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [PromoPilotDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PromoPilotDB] SET  READ_WRITE 
GO


